### ISSUE TITLE
Thank you for installing Weekly Digest

### ISSUE THREAD

**Issue by abhijeetps** [thefrontside/emberx-xml-http-request#15] opened 2018-06-13 10:49 UTC
Hi, maintainers at [thefrontside](https://github.com/thefrontside)!
Thank you for installing this app as a test in your repository. 😄 
I will be watching this repository to see app performance while it is installed.
Out of curiosity, can you please answer whether the **weekly-digest** label was 'grey' colored at the time of installing, or have you modified it. 
Thanks. 😄

**Comment by abhijeetps** [comment] 2018-06-13 10:57
That's weird, it didn't created a `.github/weekly-digest.yml` file in the repository also. 😕

**Comment by cowboyd** [comment] 2018-06-20 15:14
duplicate of #14

**Closed as completed by cowboyd** 2018-06-20 15:14 UTC
Labels: triage
